Add e2e test for HTTPS nondefault port

diff --git a/tests/e2e-leg-2/nondefault-service-ports/15-verify-services.yaml b/tests/e2e-leg-2/nondefault-service-ports/15-verify-services.yaml
--- a/tests/e2e-leg-2/nondefault-service-ports/15-verify-services.yaml
+++ b/tests/e2e-leg-2/nondefault-service-ports/15-verify-services.yaml
@@ -18,6 +18,19 @@ commands:
       sc1_ip=$(kubectl get svc -n $NAMESPACE v-nondefault-service-ports-default-subcluster -o custom-columns="CLUSTER-IP:.spec.clusterIP" --no-headers)
       sc2_ip=$(kubectl get svc -n $NAMESPACE v-nondefault-service-ports-new-subcluster -o custom-columns="CLUSTER-IP:.spec.clusterIP" --no-headers)
 
+      sc1_https=$(kubectl -n $NAMESPACE exec -it v-nondefault-service-ports-new-subcluster-0 -- curl --max-time 10 -ki https://${sc1_ip}:8448/v1/version | grep '^HTTP' | awk {'print$3'})
+      sc1_https=$(kubectl -n $NAMESPACE exec -it v-nondefault-service-ports-default-subcluster-0 -- curl --max-time 10 -ki https://${sc2_ip}:8449/v1/version | grep '^HTTP' | awk {'print$3'})
+
+      if [ -z $(echo "$sc1_https" | grep "^OK") ]; then
+        echo "Assertion failed: failed connecting to HTTPS service for subcluster v-nondefault-service-ports-default-subcluster"
+        exit 1
+      fi
+
+      if [ -z $(echo "$sc1_https" | grep "^OK") ]; then
+        echo "Assertion failed: failed connecting to HTTPS service for subcluster v-nondefault-service-ports-new-subcluster"
+        exit 1
+      fi
+
       sc1_query=$(kubectl -n $NAMESPACE exec -it v-nondefault-service-ports-new-subcluster-0 -- vsql -h $sc1_ip -p 5438 -tAc "select 1")
       sc2_query=$(kubectl -n $NAMESPACE exec -it v-nondefault-service-ports-default-subcluster-0 -- vsql -h $sc2_ip -p 5439 -tAc "select 1")
 
