fix e2e tests

diff --git a/tests/e2e-leg-9/replicated-upgrade-sanity/45-verify-sandbox-promotion.yaml b/tests/e2e-leg-9/replicated-upgrade-sanity/45-verify-sandbox-promotion.yaml
--- a/tests/e2e-leg-9/replicated-upgrade-sanity/45-verify-sandbox-promotion.yaml
+++ b/tests/e2e-leg-9/replicated-upgrade-sanity/45-verify-sandbox-promotion.yaml
@@ -21,32 +21,16 @@ data:
     set -o errexit
     set -o xtrace
 
-    POD_NAME=v-base-upgrade-pri1-sb-0
+    POD_NAMES=("v-base-upgrade-pri1-sb-0" "v-base-upgrade-pri1-sb-1" "v-base-upgrade-pri2-sb-0")
 
-    result=$(kubectl exec $POD_NAME -i -c server -- bash -c "vsql -U dbadmin -tAc \"SELECT COUNT(*) FROM nodes WHERE sandbox = 'replica-group-b';\"")
-    echo "$result" | grep -Pzo "^0\n$" > /dev/null
-    if [ $? -ne 0 ]; then
-      echo "Assertion failed: expected 0, got $result"
-      exit 1
-    fi
-
-    POD_NAME=v-base-upgrade-pri1-sb-1
-
-    result=$(kubectl exec $POD_NAME -i -c server -- bash -c "vsql -U dbadmin -tAc \"SELECT COUNT(*) FROM nodes WHERE sandbox = 'replica-group-b';\"")
-    echo "$result" | grep -Pzo "^0\n$" > /dev/null
-    if [ $? -ne 0 ]; then
-      echo "Assertion failed: expected 0, got $result"
-      exit 1
-    fi
-
-    POD_NAME=v-base-upgrade-pri2-sb-0
-
-    result=$(kubectl exec $POD_NAME -i -c server -- bash -c "vsql -U dbadmin -tAc \"SELECT COUNT(*) FROM nodes WHERE sandbox = 'replica-group-b';\"")
-    echo "$result" | grep -Pzo "^0\n$" > /dev/null
-    if [ $? -ne 0 ]; then
-      echo "Assertion failed: expected 0, got $result"
-      exit 1
-    fi
+    for POD_NAME in "${POD_NAMES[@]}"; do
+      result=$(kubectl exec $POD_NAME -i -c server -- bash -c "vsql -U dbadmin -tAc \"SELECT COUNT(*) FROM nodes WHERE sandbox = 'replica-group-b';\"")
+      echo "$result" | grep -Pzo "^0\n$" > /dev/null
+      if [ $? -ne 0 ]; then
+        echo "Assertion failed: expected 0, got $result"
+        exit 1
+      fi
+    done
 ---
 apiVersion: v1
 kind: Pod
