Address PR comments; move sandbox password change to sandbox controller; improve tests; move password cache to a generic cache

diff --git a/tests/e2e-leg-2-vc-only/password-secret-sandbox/31-verify-sandbox-superuser-password-update.yaml b/tests/e2e-leg-2-vc-only/password-secret-sandbox/31-verify-sandbox-superuser-password-update.yaml
--- a/tests/e2e-leg-2-vc-only/password-secret-sandbox/31-verify-sandbox-superuser-password-update.yaml
+++ b/tests/e2e-leg-2-vc-only/password-secret-sandbox/31-verify-sandbox-superuser-password-update.yaml
@@ -14,32 +14,33 @@
 apiVersion: v1
 kind: ConfigMap
 metadata:
-  name: script-verify-password-secret-delete
+  name: script-verify-password-secret-update-sandbox-new-subcluster
 data:
   entrypoint.sh: |-
     #!/bin/bash
     set -o errexit
     set -o xtrace
 
-    POD_NAME=v-password-secret-sandbox-sc1-0
+    POD_NAME=v-password-secret-sandbox-sc3-0
 
-    result=$(kubectl exec $POD_NAME -i -c server -- bash -c "vsql -tAc 'select password from passwords'")
-    if [ $result != "" ]; then
-      echo "Assertion failed: expected empty password, got $result"
+    result=$(kubectl exec $POD_NAME -i -c server -- bash -c "vsql -w topsecret -tAc 'select count(*) from passwords'")
+    echo "$result" | grep -Pzo '1' > /dev/null
+    if [ $? -ne 0 ]; then
+      echo "Assertion failed: expected 1, got $result"
       exit 1
     fi
 ---
 apiVersion: v1
 kind: Pod
 metadata:
-  name: test-verify-password-secret-delete
+  name: test-verify-password-secret-update-sandbox-new-subcluster
   labels:
     stern: include
 spec:
   restartPolicy: Never
   containers:
     - name: test
-      image: bitnami/kubectl:1.20.4
+      image: bitnamisecure/kubectl:latest
       command: ["/bin/entrypoint.sh"]
       volumeMounts:
         - name: entrypoint-volume
@@ -50,4 +51,4 @@ spec:
     - name: entrypoint-volume
       configMap:
         defaultMode: 0777
-        name: script-verify-password-secret-delete
+        name: script-verify-password-secret-update-sandbox-new-subcluster
