Address PR feedback

diff --git a/tests/e2e-leg-10/verify-vrep-async-options/35-verify-target-data.yaml b/tests/e2e-leg-10/verify-vrep-async-options/35-verify-target-data.yaml
--- a/tests/e2e-leg-10/verify-vrep-async-options/35-verify-target-data.yaml
+++ b/tests/e2e-leg-10/verify-vrep-async-options/35-verify-target-data.yaml
@@ -23,6 +23,7 @@ data:
 
     POD_NAMES=("v-target-sc4-0" "v-target-sc1-0")
 
+    # Verify 'test_table1' and 'test_table2' don't exist in sandboxes we haven't replicated data to
     for POD_NAME in "${POD_NAMES[@]}"; do
       result=$(kubectl exec $POD_NAME -i -c server -- bash -c "vsql -U dbadmin -tAc \"SELECT COUNT(*) FROM tables WHERE table_name = 'test_table1' OR table_name = 'test_table2';\"")
       echo "$result" | grep -Pzo "^0\n$" > /dev/null
@@ -32,24 +33,25 @@ data:
       fi
     done
 
-    POD_NAMES=("v-target-sc3-0" "v-source-sc1-0")
+    # Replication was done with the options 'includePattern: "*.test_table*"' and 'excludePattern: "*.test_table1"'
+    # Verify partial replication was done correctly on the target sandbox
+    # Verify 'test_table2' exists and has correct data
+    POD_NAME="v-target-sc3-0"
+    result=$(kubectl exec $POD_NAME -i -c server -- bash -c "vsql -U dbadmin -w superuser -tAc \"SELECT * FROM test.test_table2 ORDER BY val;\"")
+    echo "$result" | grep -Pzo "^22\n$" > /dev/null
+    if [ $? -ne 0 ]; then
+      echo "Assertion failed: expected 22, got $result"
+      exit 1
+    fi
+    result=$(kubectl exec $POD_NAME -i -c server -- bash -c "vsql -U dbadmin -w superuser -tAc \"SELECT COUNT(*) FROM tables WHERE table_name = 'test_table2';\"")
+    echo "$result" | grep -Pzo "^1\n$" > /dev/null
+    if [ $? -ne 0 ]; then
+      echo "Assertion failed: expected 1, got $result"
+      exit 1
+    fi
 
-    for POD_NAME in "${POD_NAMES[@]}"; do
-      result=$(kubectl exec $POD_NAME -i -c server -- bash -c "vsql -U dbadmin -w superuser -tAc \"SELECT * FROM test.test_table2 ORDER BY val;\"")
-      echo "$result" | grep -Pzo "^22\n$" > /dev/null
-      if [ $? -ne 0 ]; then
-        echo "Assertion failed: expected 22, got $result"
-        exit 1
-      fi
-      result=$(kubectl exec $POD_NAME -i -c server -- bash -c "vsql -U dbadmin -w superuser -tAc \"SELECT COUNT(*) FROM tables WHERE table_name = 'test_table2';\"")
-      echo "$result" | grep -Pzo "^1\n$" > /dev/null
-      if [ $? -ne 0 ]; then
-        echo "Assertion failed: expected 1, got $result"
-        exit 1
-      fi
-    done
-
-    result=$(kubectl exec v-target-sc3-0 -i -c server -- bash -c "vsql -U dbadmin -w superuser -tAc \"SELECT COUNT(*) FROM tables WHERE table_name = 'test_table1';\"")
+    # Verify 'test_table1' does not exist since it was excluded
+    result=$(kubectl exec $POD_NAME -i -c server -- bash -c "vsql -U dbadmin -w superuser -tAc \"SELECT COUNT(*) FROM tables WHERE table_name = 'test_table1';\"")
     echo "$result" | grep -Pzo "^0\n$" > /dev/null
     if [ $? -ne 0 ]; then
       echo "Assertion failed: expected 0, got $result"
diff --git a/tests/e2e-leg-10/verify-vrep-async-options/50-verify-target-data-target-namespace.yaml b/tests/e2e-leg-10/verify-vrep-async-options/50-verify-target-data-target-namespace.yaml
--- a/tests/e2e-leg-10/verify-vrep-async-options/50-verify-target-data-target-namespace.yaml
+++ b/tests/e2e-leg-10/verify-vrep-async-options/50-verify-target-data-target-namespace.yaml
@@ -21,8 +21,19 @@ data:
     set -o errexit
     set -o xtrace
 
-    POD_NAME="v-target-sc4-0"
+    # Verify 'test_table1' and 'test_table2' don't exist in the sandbox we haven't replicated data to
+    POD_NAME="v-target-sc1-0"
+    result=$(kubectl exec $POD_NAME -i -c server -- bash -c "vsql -U dbadmin -tAc \"SELECT COUNT(*) FROM tables WHERE table_name = 'test_table1' OR table_name = 'test_table2';\"")
+    echo "$result" | grep -Pzo "^0\n$" > /dev/null
+    if [ $? -ne 0 ]; then
+      echo "Assertion failed: expected 0, got $result"
+      exit 1
+    fi
 
+    # Replication was done with the options 'includePattern: "test.*"' and 'target.namespace: "target_test"'
+    # Verify partial replication was done correctly on the target sandbox
+    # Verify both 'test_table1' and 'test_table2' exist in the new namespace and have correct data
+    POD_NAME="v-target-sc4-0"
     result=$(kubectl exec $POD_NAME -i -c server -- bash -c "vsql -U dbadmin -w superuser -tAc \"SELECT * FROM target_test.test.test_table1 ORDER BY val;\"")
     echo "$result" | grep -Pzo "^11\n$" > /dev/null
     if [ $? -ne 0 ]; then
