check custom username/password

diff --git a/tests/e2e-leg-9/verify-vrep/05-create-source-data.yaml b/tests/e2e-leg-9/verify-vrep/05-create-source-data.yaml
--- a/tests/e2e-leg-9/verify-vrep/05-create-source-data.yaml
+++ b/tests/e2e-leg-9/verify-vrep/05-create-source-data.yaml
@@ -36,13 +36,19 @@ data:
       echo "Assertion failed: expected 1, got $result"
       exit 1
     fi
-    POD_NAME=v-target-sc1-0
-    result=$(kubectl exec $POD_NAME -i -c server -- bash -c "vsql -U dbadmin -tAc \"SELECT COUNT(*) FROM tables;\"")
-    echo "$result" | grep -Pzo "^0\n$" > /dev/null
-    if [ $? -ne 0 ]; then
-      echo "Assertion failed: expected 0, got $result"
-      exit 1
-    fi
+
+    POD_NAMES=("v-target-sc4-0" "v-target-sc3-0" "v-target-sc2-0" "v-target-sc1-0")
+
+    for POD_NAME in "${POD_NAMES[@]}"; do
+      kubectl exec $POD_NAME -i -c server -- bash -c "vsql -U dbadmin -tAc \"CREATE USER custom_user_with_password IDENTIFIED BY 'topsecret'; GRANT PSEUDOSUPERUSER TO custom_user_with_password; ALTER USER custom_user_with_password DEFAULT ROLE PSEUDOSUPERUSER;\""
+      kubectl exec $POD_NAME -i -c server -- bash -c "vsql -U dbadmin -tAc \"CREATE USER custom_user; GRANT PSEUDOSUPERUSER TO custom_user; ALTER USER custom_user DEFAULT ROLE PSEUDOSUPERUSER;\""
+      result=$(kubectl exec $POD_NAME -i -c server -- bash -c "vsql -U dbadmin -tAc \"SELECT COUNT(*) FROM tables;\"")
+      echo "$result" | grep -Pzo "^0\n$" > /dev/null
+      if [ $? -ne 0 ]; then
+        echo "Assertion failed: expected 0, got $result"
+        exit 1
+      fi
+    done
 ---
 apiVersion: v1
 kind: Pod
diff --git a/tests/e2e-leg-9/verify-vrep/20-verify-target-data.yaml b/tests/e2e-leg-9/verify-vrep/20-verify-target-data.yaml
--- a/tests/e2e-leg-9/verify-vrep/20-verify-target-data.yaml
+++ b/tests/e2e-leg-9/verify-vrep/20-verify-target-data.yaml
@@ -21,39 +21,39 @@ data:
     set -o errexit
     set -o xtrace
 
-    POD_NAME=v-target-sc2-0
-    result=$(kubectl exec $POD_NAME -i -c server -- bash -c "vsql -U dbadmin -tAc \"SELECT COUNT(*) FROM tables;\"")
-    echo "$result" | grep -Pzo "^0\n$" > /dev/null
-    if [ $? -ne 0 ]; then
-      echo "Assertion failed: expected 0, got $result"
-      exit 1
-    fi
-    POD_NAME=v-target-sc1-0
-    result=$(kubectl exec $POD_NAME -i -c server -- bash -c "vsql -U dbadmin -tAc \"SELECT * FROM public.test_table ORDER BY val;\"")
-    echo "$result" | grep -Pzo "^99\n$" > /dev/null
-    if [ $? -ne 0 ]; then
-      echo "Assertion failed: expected 99, got $result"
-      exit 1
-    fi
-    result=$(kubectl exec $POD_NAME -i -c server -- bash -c "vsql -U dbadmin -tAc \"SELECT COUNT(*) FROM tables;\"")
-    echo "$result" | grep -Pzo "^1\n$" > /dev/null
-    if [ $? -ne 0 ]; then
-      echo "Assertion failed: expected 1, got $result"
-      exit 1
-    fi
-    POD_NAME=v-source-sc1-0
-    result=$(kubectl exec $POD_NAME -i -c server -- bash -c "vsql -U dbadmin -w superuser -tAc \"SELECT * FROM public.test_table ORDER BY val;\"")
-    echo "$result" | grep -Pzo "^99\n$" > /dev/null
-    if [ $? -ne 0 ]; then
-      echo "Assertion failed: expected 99, got $result"
-      exit 1
-    fi
-    result=$(kubectl exec $POD_NAME -i -c server -- bash -c "vsql -U dbadmin -w superuser -tAc \"SELECT COUNT(*) FROM tables;\"")
-    echo "$result" | grep -Pzo "^1\n$" > /dev/null
-    if [ $? -ne 0 ]; then
-      echo "Assertion failed: expected 1, got $result"
-      exit 1
-    fi
+    POD_NAMES=("v-target-sc4-0" "v-target-sc3-0" "v-target-sc2-0")
+
+    for POD_NAME in "${POD_NAMES[@]}"; do
+      result=$(kubectl exec $POD_NAME -i -c server -- bash -c "vsql -U dbadmin -tAc \"SELECT COUNT(*) FROM tables;\"")
+      echo "$result" | grep -Pzo "^0\n$" > /dev/null
+      if [ $? -ne 0 ]; then
+        echo "Assertion failed: expected 0, got $result"
+        exit 1
+      fi
+      result=$(kubectl exec $POD_NAME -i -c server -- bash -c "vsql -U dbadmin -tAc \"SELECT COUNT(*) FROM tables;\"")
+      echo "$result" | grep -Pzo "^0\n$" > /dev/null
+      if [ $? -ne 0 ]; then
+        echo "Assertion failed: expected 0, got $result"
+        exit 1
+      fi
+    done
+
+    POD_NAMES=("v-target-sc1-0" "v-source-sc1-0")
+
+    for POD_NAME in "${POD_NAMES[@]}"; do
+      result=$(kubectl exec $POD_NAME -i -c server -- bash -c "vsql -U dbadmin -w superuser -tAc \"SELECT * FROM public.test_table ORDER BY val;\"")
+      echo "$result" | grep -Pzo "^99\n$" > /dev/null
+      if [ $? -ne 0 ]; then
+        echo "Assertion failed: expected 99, got $result"
+        exit 1
+      fi
+      result=$(kubectl exec $POD_NAME -i -c server -- bash -c "vsql -U dbadmin -w superuser -tAc \"SELECT COUNT(*) FROM tables;\"")
+      echo "$result" | grep -Pzo "^1\n$" > /dev/null
+      if [ $? -ne 0 ]; then
+        echo "Assertion failed: expected 1, got $result"
+        exit 1
+      fi
+    done
 ---
 apiVersion: v1
 kind: Pod
