test sandbox

diff --git a/tests/e2e-leg-9/verify-vrep/35-verify-target-sandbox-data.yaml b/tests/e2e-leg-9/verify-vrep/35-verify-target-sandbox-data.yaml
--- a/tests/e2e-leg-9/verify-vrep/35-verify-target-sandbox-data.yaml
+++ b/tests/e2e-leg-9/verify-vrep/35-verify-target-sandbox-data.yaml
@@ -22,10 +22,16 @@ data:
     set -o xtrace
 
     POD_NAME=v-target-sc2-0
-    result=$(kubectl exec $POD_NAME -i -c server -- bash -c "vsql -U dbadmin -tAc \"SELECT COUNT(*) FROM tables;\"")
-    echo "$result" | grep -Pzo "^0\n$" > /dev/null
+    result=$(kubectl exec $POD_NAME -i -c server -- bash -c "vsql -U dbadmin -tAc \"SELECT * FROM public.test_table ORDER BY val;\"")
+    echo "$result" | grep -Pzo "^99\n$" > /dev/null
     if [ $? -ne 0 ]; then
-      echo "Assertion failed: expected 0, got $result"
+      echo "Assertion failed: expected 99, got $result"
+      exit 1
+    fi
+    result=$(kubectl exec $POD_NAME -i -c server -- bash -c "vsql -U dbadmin -tAc \"SELECT COUNT(*) FROM tables;\"")
+    echo "$result" | grep -Pzo "^1\n$" > /dev/null
+    if [ $? -ne 0 ]; then
+      echo "Assertion failed: expected 1, got $result"
       exit 1
     fi
     POD_NAME=v-target-sc1-0
