tls config test

diff --git a/tests/e2e-leg-9/verify-vrep/50-verify-target-sandbox-data-custom-username.yaml b/tests/e2e-leg-9/verify-vrep/50-verify-target-sandbox-data-custom-username.yaml
--- a/tests/e2e-leg-9/verify-vrep/50-verify-target-sandbox-data-custom-username.yaml
+++ b/tests/e2e-leg-9/verify-vrep/50-verify-target-sandbox-data-custom-username.yaml
@@ -21,6 +21,17 @@ data:
     set -o errexit
     set -o xtrace
 
+    POD_NAMES=("v-target-sc5-0")
+
+    for POD_NAME in "${POD_NAMES[@]}"; do
+      result=$(kubectl exec $POD_NAME -i -c server -- bash -c "vsql -U dbadmin -tAc \"SELECT COUNT(*) FROM tables;\"")
+      echo "$result" | grep -Pzo "^0\n$" > /dev/null
+      if [ $? -ne 0 ]; then
+        echo "Assertion failed: expected 0, got $result"
+        exit 1
+      fi
+    done
+
     POD_NAMES=("v-target-sc4-0" "v-target-sc3-0" "v-target-sc2-0" "v-target-sc1-0" "v-source-sc1-0")
 
     for POD_NAME in "${POD_NAMES[@]}"; do
