Update auto-scaling test

diff --git a/tests/e2e-leg-12/scale-down-db-with-threshold-hpa/30-verify-prometheus-adapter.yaml b/tests/e2e-leg-12/scale-down-db-with-threshold-hpa/30-verify-prometheus-adapter.yaml
--- a/tests/e2e-leg-12/scale-down-db-with-threshold-hpa/30-verify-prometheus-adapter.yaml
+++ b/tests/e2e-leg-12/scale-down-db-with-threshold-hpa/30-verify-prometheus-adapter.yaml
@@ -11,11 +11,13 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-apiVersion: vertica.com/v1beta1
-kind: VerticaAutoscaler
-metadata:
-  name: v-autoscale
-status:
-  selector: vertica.com/subcluster-svc=as,vertica.com/is-sandbox=false,app.kubernetes.io/instance=v-autoscale-by-subcluster,app.kubernetes.io/managed-by=verticadb-operator
-  scalingCount: 0
-  currentSize: 0
+apiVersion: kuttl.dev/v1beta1
+kind: TestStep
+commands:
+  - script: |
+      RESULT=$(kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1)
+      VERSION=$(echo $RESULT | jq -r '.groupVersion')
+      if [ "$VERSION" != "custom.metrics.k8s.io/v1beta1" ]; then
+        echo "Assertion failed: expected group version custom.metrics.k8s.io/v1beta1, got $VERSION."
+        exit 1
+      fi
