Fix e2e failures
Two fixes here:
- timing window in operator-metrics.  The guage for pod readyiness might
  not yet be updated when we check, even though the pod is ready.
  Adding a retry method.
- Saw failures in upgrade-vertica-ks-0.  If we don't include all of the
  pods in the start_db command, we can get stuck.  Then attempts after
  to get podfacts die because the vsql commands fail.

diff --git a/tests/e2e-extra/operator-metrics/30-verify-metrics-endpoint.yaml b/tests/e2e-extra/operator-metrics/30-verify-metrics-endpoint.yaml
--- a/tests/e2e-extra/operator-metrics/30-verify-metrics-endpoint.yaml
+++ b/tests/e2e-extra/operator-metrics/30-verify-metrics-endpoint.yaml
@@ -36,8 +36,21 @@ data:
     for sc in pri-sc sec-sc
     do
         curl http://$SVC_NAME:8443/metrics | grep "verticadb_subclusters_pod_count{subcluster=\"$sc\",verticadb=\"v-operator-metrics\"} 1"
-        curl http://$SVC_NAME:8443/metrics | grep "verticadb_subclusters_ready_pod_count{subcluster=\"$sc\",verticadb=\"v-operator-metrics\"} 1"
         curl http://$SVC_NAME:8443/metrics | grep "verticadb_subclusters_running_pod_count{subcluster=\"$sc\",verticadb=\"v-operator-metrics\"} 1"
+    done
+    # These is timing with the ready pod count.  The pod may be ready but the
+    # metrics haven't yet been updated.  We check that a few times before
+    # failing the test.
+    for sc in pri-sc sec-sc
+    do
+      for i in $(seq 1 5)
+      do
+        [ $i -gt 1 ] && sleep 10
+        curl http://$SVC_NAME:8443/metrics
+        curl http://$SVC_NAME:8443/metrics | grep "verticadb_subclusters_ready_pod_count{subcluster=\"$sc\",verticadb=\"v-operator-metrics\"} 1" \
+          && s=0 && break || s=$?
+      done
+      (exit $s)
     done
 ---
 apiVersion: v1
