Add support for rockylinux 8 in our server container (#665)
This adds support for rockylinux 8 in our container builds. Now we can
switch between version 8 and 9 through make variables. Rockylinux 8 is
the default for new server containers going forward. This applies both
to the v1 and v2 vertica images. The first publicly available image with
rockylinux 8 will be 24.2.0.

In order to support both versions, the udx e2e testcase setup had to
change a bit. I think its easier to run that now on your local machine.

vdb-gen had to compile in static libraries for libc so that one compiled
on a newer OS can run on rockylinux 8.

diff --git a/.github/workflows/e2e-udx.yml b/.github/workflows/e2e-udx.yml
--- a/.github/workflows/e2e-udx.yml
+++ b/.github/workflows/e2e-udx.yml
@@ -71,13 +71,15 @@ jobs:
         export VLOGGER_IMG=${{ inputs.vlogger-image }}
         export E2E_TEST_DIRS=tests/e2e-udx
         export VERTICA_DEPLOYMENT_METHOD=${{ inputs.vertica-deployment-method }}
-        export JAVA_HOME=${JAVA_HOME_8_X64}  # We need a java version that matches the one in the Vertica image
-        java --version
-        # Install system packages that some of the tests depend on.  Any
-        # changes here need to be duplicated in udx-cpp/30-upload-files.yaml
-        # We retry the command to avoid any interimittent network issues.
-        for i in $(seq 1 5); do sudo apt-get update && sudo apt-get install -y libboost-all-dev libcurl4-openssl-dev libbz2-dev && break || sleep 60; done
-        scripts/setup-e2e-udx.sh -v
+        # Setup the udx environment by compiling examples in the vertica image.
+        # This downloads packages, so to improve its reliability we retry in
+        # case any intermittent network issues arise.
+        for i in $(seq 1 5); do scripts/setup-e2e-udx.sh -v && s=0 && break || s=$? && sleep 60; done
+        if [[ $s != "0" ]]
+        then
+          echo "*** Give up trying to setup the udx env"
+          exit 1
+        fi
         scripts/run-k8s-int-tests.sh -s -e tests/external-images-s3-ci.txt
 
     - uses: actions/upload-artifact@v3
